-- ============================================================
-- Chess Platform – Phase D  |  AlterTable.sql
-- Students: Elazar Krispel (8309), Alon Greenstein (7002)
-- ============================================================
--
-- NO STRUCTURAL CHANGES WERE REQUIRED IN PHASE D.
--
-- Every function, procedure and trigger written in this phase works
-- directly on the integrated schema produced in Phase C (27 tables,
-- restored from "שלב ג/backup3.sql").
--
-- Design decisions that made this possible:
--
--   1. No audit / log tables were added.
--      Proof that a program ran is provided by RAISE NOTICE output,
--      by RAISE EXCEPTION screenshots, and by SELECT-before / SELECT-after
--      inside a transaction (see the demo sections of each program file).
--
--   2. No denormalized columns (total_logins, last_login_date, ...) were
--      added. Every value the programs need is computed from the existing
--      data at run time.
--
--   3. fn_player_activity_score RETURNS the score instead of storing it,
--      so no result table is needed and the function stays side-effect free.
--
--   4. Time windows are computed relative to MAX(login_log.login_date)
--      (the newest row in the data is 2026-03-24) instead of CURRENT_DATE,
--      so no data had to be back-dated or inserted.
--
-- This file is intentionally free of DDL. It is kept in the submission so
-- that the decision "no schema change was needed" is documented explicitly.
-- ============================================================
